apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-kuxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-kuxy
    app.kubernetes.io/part-of: build-suite-positive-mc-uygk
  name: go-component-kuxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-component-kuxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-component-kuxy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-bsve-tenant/build-suite-positive-mc-uygk/go-component-kuxy@sha256:946d110b39ce9cad7582e6408cd5237f5678bbceede5758db80546e370dbf421
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
